### ISSUE TITLE
HEX colors

### ISSUE THREAD

**Issue by LuuckA21** [RienBijl/Scoreboard-revision#1]
Hi, is possible to implemente HEX in this pattern? &#fcba03

**Comment by RienBijl** [comment]
Well its certainly possible. What is the benefit of that?

**Comment by LuuckA21** [comment]
Because, Luckperms, essentials and other plugins use pattern like &#fcba03. And for example I can use HEX {#fcba03} for LuckPerms.

**Comment by RienBijl** [comment]
But does it actually break something. I would really like the format not to end with the hex-code, simply because it's a lot cleaner.
Like, does it break placeholders or anything?

**Comment by LuuckA21** [comment]
I use HEX color in Luckperms and placeholder in Scoreboard to see your prefix. And with {} pattern does not work.

**Comment by RienBijl** [comment]
Ah I see, here's what I will do:
- In the configuration I will keep the {#00000} format
- I will parse both formats on the end results from placeholders

This way there won't be a mess in the configuration and it will support the format of the aforementioned plugins.
Would that work?

**Comment by LuuckA21** [comment]
I think can work. Thank you

**Comment by RienBijl** [comment]
I will not release the update right away, because I want to implement some additional things for the next update. But I will send a JAR with that fixed in this issue thread, so you can implement it right away. Might be a few minutes.

**Comment by RienBijl** [comment]
https://github.com/RienBijl/Scoreboard-revision/releases/tag/r4-1.2

Could you try that jar file, see if it resolves your issue :)

**Comment by LuuckA21** [comment]
Thank you, tomorrow I will try it.

**Comment by RienBijl** [comment]
Than I will close this for now, thanks for the issue :)
