### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by Decme** [RienBijl/Scoreboard-revision#3]
Can't post on Spigot because don't have a Spigot account (and don't want one) I've installed the plugin but there are no guidelines on how to modify the settings.yml

**Comment by RienBijl** [comment]
You don't need a spigot account to read the instructions on the plugin page.

**Comment by Decme** [comment]
And yet, it doesn't work. For example '%player_name%' will display literally %player_name% instead of the player's actual name, and this goes for every variable. Assuming there's a way to get the variables working, what would the variable for TPS be? TPS is all I would like to have displayed.

**Comment by RienBijl** [comment]
> read the instructions on the plugin page.

`Before you review or submit a bug that the variables don't work, remember to install PlaceholderAPI by extended_clip and use:
- /papi ecloud download Player
- /papi ecloud download Server
- /papi ecloud download Essentials`
