### ISSUE TITLE
Line appended with nonsense color codes, causing it to be too long.

### ISSUE THREAD

**Issue by DePianoman** [RienBijl/Scoreboard-revision#5]
This is similar to LucKYsHoTSzZz's post, however his just claims that a string obv. less than 16 characters has more. In my settings.yml, I have the line
```
    2:
      interval: 80
      liner:
      - '&a&lOnline:'
```
and it does not show up, outputting this in the console:
![error](https://user-images.githubusercontent.com/23054839/50368710-d24cfd80-0559-11e9-99a7-c448a04c6e76.png)
As you can see, it is appending &f&a&l for seemingly no reason, causing it to be 17 characters long.

**Comment by RienBijl** [comment]
317df8e
