### ISSUE TITLE
Placeholder doesnt replace

### ISSUE THREAD

**Issue by Invouker** [RienBijl/Scoreboard-revision#5]
**Describe the bug**
Placeolderapi doesnt fill with correct data after restart the server. 

**To Reproduce**
1. Just restart the server and this happens but if you gonna use a plugman reload, it will be good

**Expected behavior**
Replace placeholder with correct data. 

**Screenshots**
![unknown.png](https://user-images.githubusercontent.com/30478987/112482318-39307100-8d78-11eb-94e7-9132ee3b49c7.png)

**Spigot version(please complete the following information):**
 - Paper, 1.16.5

**Comment by RienBijl** [comment]
Could you please add a list of plugins

**Comment by Invouker** [comment]
![image](https://user-images.githubusercontent.com/30478987/112538901-a6f88f00-8db0-11eb-9933-fbf8395111a3.png)
There is a plugin list,

**Comment by EagL3-GIT** [comment]
@RienBijl

**Comment by RienBijl** [comment]
Replies will be a bit slow, I'm recovering from an RSI so my progress is slower than usual

**Comment by EagL3-GIT** [comment]
@RienBijl so? Can u finally fix ur issue please?

**Comment by EagL3-GIT** [comment]
Alright, keep ur broken plugin then.

**Comment by RoloRotMG** [comment]
> 
> 
> Alright, keep ur broken plugin then.

I'm getting second hand embarrassment from how rude you are.

**Comment by RienBijl** [comment]
> Alright, keep ur broken plugin then.

It's a free plugin I make in my spare time, I don't charge anything for it nor do I accept donations. As I said before, I am recovering from an [RSI](https://en.wikipedia.org/wiki/Repetitive_strain_injury), progress will be slow.

You are not entitled to support and frequent bugfixes, but I provide them anyway, just not always in a timely manner. For the sake of other users who might have the same problem I will keep this issue open.

**Comment by Sjoerd** [comment]
I tried to reproduce it, doesn't happen on my server.
