### ISSUE TITLE
Distracting and unprofessional console logging

### ISSUE THREAD

**Issue by kmecpp** [RienBijl/Scoreboard-revision#7]
Please add a config setting to allow disabling the obnoxious console ASCII art

![image](https://user-images.githubusercontent.com/6520738/55248320-f0dd2780-521f-11e9-85a2-fa3bbbd79189.png)

**Comment by RienBijl** [comment]
https://github.com/RienBijl/Scoreboard-revision/projects/1

Exception boarded and will look into

**Comment by RienBijl** [comment]
This has been removed from the plugin.
