### ISSUE TITLE
Scoreboard doesn't show when I join

### ISSUE THREAD

**Issue by Paperboypaddy** [RienBijl/Scoreboard-revision#8]
Hello I have a pretty big but simple issue, when I join my server it doesn't show the scoreboard. I have to reload the plugin with /sb reload, only once I do that it shows the scoreboard.

Edit: I looked in my console and sure enough there's a error!
```02.04 11:35:30 [Server] ERROR Could not pass event PlayerJoinEvent to Scoreboard-revision vR3 1.3.1 RELEASE
02.04 11:35:30 [Server] INFO org.bukkit.event.EventException: null
02.04 11:35:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
02.04 11:35:30 [Server] INFO Caused by: java.lang.NoSuchMethodError: rien.bijl.Scoreboard.r.board.App.isCancelled()Z
02.04 11:35:30 [Server] INFO at rien.bijl.Scoreboard.r.board.events.EIntergrate.Intergrate(EIntergrate.java:26) ~[?:?]
02.04 11:35:30 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
02.04 11:35:30 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
02.04 11:35:30 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
02.04 11:35:30 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
02.04 11:35:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[1.12.jar:git-Spigot-596221b-9a1fc1e]
02.04 11:35:30 [Server] INFO ... 14 more```

**Comment by RasmonT** [comment]
I think there is some code missing that will launch the scoreboard on playerjoin... I have same problem and i will try to look into it if i can fix this or not ... Unfortunately the dev seems no active right now... @Paperboypaddy or have you fixed this problem somehow ?

**Comment by RasmonT** [comment]
@Paperboypaddy For temporary fix you can use JoinCommands plugin to execute command for players automatically . This worked for me perfectly.

**Comment by Paperboypaddy** [comment]
@RasmonT What cmd are you having it execute? And i did find a substitute for this plugin https://www.spigotmc.org/resources/15057/
Only thing is this plugin is a little broken for me, i have it setup for a different scoreboard each world and it doesnt change the scoreboard when you change worlds. But i think i can work of fixing that plugin. This one seems harder bc i need all the dependencies for it ig?

**Comment by RasmonT** [comment]
scoreboardCommand:
    command: '[PLAYER]sb reload'

    delay: 200 // 10 seconds

    permission: ''

    first join only: false

    scoreboardCommand1:
    command: '[PLAYER]sb reload'

    delay: 400 //20 seconds

    permission: ''

    first join only: false`

This is example of config, i have it putted twice there because when user is not authoriyed by authMe the board won't load... I used this plugin https://www.spigotmc.org/resources/join-commands.51758/  .

**Comment by Paperboypaddy** [comment]
you should use my plugin XDDD JK JK https://www.spigotmc.org/resources/joincommands.64769/

**Comment by RasmonT** [comment]
:D Interesting, well i just found a simple solution for loading scoreboard for players automatically with help from plugin.. I hope later on Author will add function that board will be showing by default when player joins server .

**Comment by Paperboypaddy** [comment]
yeah same!

**Comment by RasmonT** [comment]
@Paperboypaddy Unfortunately i have some strange issue with the plugin do you know how to fix ? 

    rows:
    1:
      interval: 5
      liner:
      - '&3Hráč:'
    2:
      interval: 80
      liner:
      - '&bRank:'
    3:
      interval: 80
      liner:
      - '&c%vault_rank%'
    4:
      interval: 80
      liner:
      - '&2Peniaze:'
    5:
      liner:
      - '&e%vault_eco_balance%&a$'

When i have more than 100k+ cash i see this bullshit.. 
![IDEAS](https://user-images.githubusercontent.com/35234558/56399250-225c7800-624d-11e9-90ae-61fa0c2f7d13.png)

**Comment by RienBijl** [comment]
https://github.com/RienBijl/Scoreboard-revision/projects/1

Exception boarded and will look into

**Comment by Paperboypaddy** [comment]
> https://github.com/RienBijl/Scoreboard-revision/projects/1
> 
> Exception boarded and will look into

Ok thanks

**Comment by RienBijl** [comment]
Should be resolved.
